### ISSUE TITLE
Have multiple Phone Numbers exported?

### ISSUE THREAD

**Issue by Nilsemann** [sidedwards/contacts-exporter#1]
Hi, I love your script, and I modified it a bit. - I have everything also as Metadata written into frontmatter.

I have tried a bit... but many of my contacts have more than one phone number, privat, business, cell... most of them:

TEL;type=CELL;type=VOICE;type=pref:+44xxx
TEL;type=WORK;type=VOICE:+44xxxx

Your script will only take care of the first TEL entry in the VCard. I wonder if that could be modified to export more than one?

Simliar challange with ADR - I have a work and home address...

**Comment by sidedwards** [comment]
Good idea, thanks! I added here 94fa45c.
